# Generated by Django 4.2.5 on 2023-09-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_remove_pacient_info_method_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
