# Generated by Django 4.2.5 on 2023-09-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0007_detail_keys_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='doctors_ques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='keyb_quest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
