# Generated by Django 4.2.5 on 2023-09-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0008_questions_doctors_ques_questions_keyb_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient_info',
            name='total',
            field=models.TextField(blank=True, null=True),
        ),
    ]
