# Generated by Django 4.2.5 on 2023-09-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0009_alter_pacient_info_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect_admin',
            name='keyb_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
