# Generated by Django 4.2.5 on 2023-09-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0010_connect_admin_keyb_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory_analice',
            name='keyb_text',
            field=models.CharField(blank=True, default='Открыть в Google Maps', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mskt_book',
            name='keyb_text',
            field=models.CharField(blank=True, default='Открыть в Google Maps', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='recomended_centers',
            name='keyb_text',
            field=models.CharField(blank=True, default='Открыть в Google Maps', max_length=250, null=True),
        ),
    ]
