# Generated by Django 4.2.5 on 2023-09-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0011_laboratory_analice_keyb_text_mskt_book_keyb_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='another_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back', models.CharField(max_length=250)),
                ('previous', models.CharField(max_length=250)),
                ('select_doctor', models.CharField(max_length=250)),
            ],
        ),
    ]
