# Generated by Django 4.2.5 on 2023-09-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0012_another_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='another_text',
            name='ask_question',
            field=models.CharField(default='Задать вопрос', max_length=250),
        ),
    ]
