# Generated by Django 4.2.5 on 2023-09-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0015_questions_type_quest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='type_quest',
        ),
    ]
