# Generated by Django 4.2.5 on 2023-09-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0017_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='language_code',
            field=models.CharField(blank=True, choices=[(0, "O'zbekcha"), (1, 'Русский')], max_length=10, null=True),
        ),
    ]
