# Generated by Django 4.2.5 on 2023-09-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0018_users_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='language_code',
            field=models.CharField(blank=True, choices=[(0, 'Русский'), (1, "O'zbekcha")], max_length=10, null=True),
        ),
    ]
