# Generated by Django 4.2.5 on 2023-09-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0020_another_text_start_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='offline_price',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='online_price',
            field=models.CharField(max_length=250),
        ),
    ]
