# Generated by Django 4.2.5 on 2023-09-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0021_alter_doctors_offline_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='url',
        ),
        migrations.AddField(
            model_name='doctors',
            name='user_id',
            field=models.BigIntegerField(default=511172905),
        ),
        migrations.AddField(
            model_name='payment',
            name='token',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
