# Generated by Django 4.2.5 on 2023-09-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0022_remove_payment_url_doctors_user_id_payment_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('group_id', models.BigIntegerField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('status_working', models.BooleanField(default=False)),
            ],
        ),
    ]
