# Generated by Django 4.2.5 on 2023-09-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0024_group_info_link_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='calls_price',
            field=models.CharField(default="💻 Онлайн консультация (звонок/видео) – 20$⌛️30 минут^^^💻 Onlayn maslahat (qo'ng'iroq/video) – 20$⌛️30 daqiqa", max_length=350),
        ),
        migrations.AddField(
            model_name='doctors',
            name='chat_price',
            field=models.CharField(default='💬 Консультация в чате – 14$ ^^^💬 Chatda maslahat – $14', max_length=350),
        ),
        migrations.AddField(
            model_name='doctors',
            name='consult_type',
            field=models.TextField(choices=[('calls', 'Calls'), ('chat', 'Chat'), ('calls/chat', 'Calls/Chat')], default='calls/chat', max_length=150),
        ),
    ]
