# Generated by Django 4.2.5 on 2023-09-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0025_doctors_calls_price_doctors_chat_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_info',
            name='doctor_user_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='group_info',
            name='pacient_userid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
