# Generated by Django 4.2.5 on 2023-09-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0026_group_info_doctor_user_id_group_info_pacient_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_info',
            name='users_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
