# Generated by Django 4.2.5 on 2023-09-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0027_group_info_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_info',
            name='description',
            field=models.TextField(blank=True, default='админ добавь!!!', null=True),
        ),
    ]
