# Generated by Django 4.2.5 on 2023-09-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0028_group_info_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='another_text',
            name='warning_text',
            field=models.TextField(default="вы начали заполнять заявку, но так и не оформили консультацию нашего специалиста. Что вас остановило? Вы могли бы написать оператору в чем проблема?^^^siz arizani to'ldirishni boshladingiz, lekin hech qachon biz bilan maslahatlashmagan mutaxassis Sizni nima to'xtatdi? Siz Bu haqda operatorga yoza olasizmi? muammo?"),
        ),
    ]
