# Generated by Django 4.2.5 on 2023-09-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0029_another_text_warning_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='another_text',
            name='warning_keyb',
            field=models.TextField(default='Написать оператору\nОтмена заявки^^^Operatorga yozish\nArizani bekor qilish'),
        ),
    ]
