# Generated by Django 4.2.5 on 2023-09-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0030_another_text_warning_keyb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О проекте', 'verbose_name_plural': 'О проекте'},
        ),
        migrations.AlterModelOptions(
            name='admin_info',
            options={'verbose_name': 'Администраторы', 'verbose_name_plural': 'Администраторы'},
        ),
        migrations.AlterModelOptions(
            name='cat_offline',
            options={'verbose_name': 'Консультация', 'verbose_name_plural': 'Консультация'},
        ),
        migrations.AlterModelOptions(
            name='detail',
            options={'verbose_name': 'Подробное читать', 'verbose_name_plural': 'Подробное читать'},
        ),
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name': 'Доктора', 'verbose_name_plural': 'Доктора'},
        ),
        migrations.AlterModelOptions(
            name='head',
            options={'verbose_name': 'Главный меню', 'verbose_name_plural': 'Главный меню'},
        ),
        migrations.AlterModelOptions(
            name='pacient_info',
            options={'verbose_name': 'Пациенты', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платежные системы', 'verbose_name_plural': 'Платежные системы'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Вопросы', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='sub_cat_offline',
            options={'verbose_name': 'Подкатегория консультации', 'verbose_name_plural': 'Подкатегория консультации'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='payment_history',
            name='pacient',
        ),
        migrations.RemoveField(
            model_name='payment_history',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment_history',
            name='amount',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_history',
            name='user_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
