# Generated by Django 4.2.5 on 2023-09-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0031_alter_about_options_alter_admin_info_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='another_text',
            options={'verbose_name': 'Другие тексты', 'verbose_name_plural': 'Другие тексты'},
        ),
        migrations.AlterModelOptions(
            name='connect_admin',
            options={'verbose_name': 'Связаться с администратором', 'verbose_name_plural': 'Связаться с администратором'},
        ),
        migrations.AlterModelOptions(
            name='group_info',
            options={'verbose_name': 'Группы', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='laboratory_analice',
            options={'verbose_name': 'Лаборатория', 'verbose_name_plural': 'Лаборатория'},
        ),
        migrations.AlterModelOptions(
            name='mskt_book',
            options={'verbose_name': 'МСКТ', 'verbose_name_plural': 'МСКТ'},
        ),
        migrations.AlterModelOptions(
            name='payment_history',
            options={'verbose_name': 'История оплаты', 'verbose_name_plural': 'История оплаты'},
        ),
        migrations.AlterModelOptions(
            name='recomended_centers',
            options={'verbose_name': 'Рекомендуемые центры', 'verbose_name_plural': 'Рекомендуемые центры'},
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='admin_info',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='another_text',
            name='ask_question',
            field=models.CharField(default='Задать вопрос', max_length=250, verbose_name='Задать вопрос'),
        ),
        migrations.AlterField(
            model_name='another_text',
            name='back',
            field=models.CharField(max_length=250, verbose_name='Вернуться назад'),
        ),
        migrations.AlterField(
            model_name='another_text',
            name='previous',
            field=models.CharField(max_length=250, verbose_name='Назад'),
        ),
        migrations.AlterField(
            model_name='another_text',
            name='share_contact',
            field=models.CharField(default='Поделиться номер телефоном', max_length=250, verbose_name='Поделиться номер телефоном'),
        ),
        migrations.AlterField(
            model_name='another_text',
            name='start_text',
            field=models.TextField(default='Приветствуем в боте проекта TezShifo!\nМы за то, чтобы качественная медицинская помощь была доступна каждому.', verbose_name='Текст стартового сообщения'),
        ),
        migrations.AlterField(
            model_name='another_text',
            name='warning_keyb',
            field=models.TextField(default='Написать оператору\nОтмена заявки^^^Operatorga yozish\nArizani bekor qilish', verbose_name='Кнопки предупреждения'),
        ),
        migrations.AlterField(
            model_name='another_text',
            name='warning_text',
            field=models.TextField(default="вы начали заполнять заявку, но так и не оформили консультацию нашего специалиста. Что вас остановило? Вы могли бы написать оператору в чем проблема?^^^siz arizani to'ldirishni boshladingiz, lekin hech qachon biz bilan maslahatlashmagan mutaxassis Sizni nima to'xtatdi? Siz Bu haqda operatorga yoza olasizmi? muammo?", verbose_name='Текст предупреждения'),
        ),
        migrations.AlterField(
            model_name='cat_offline',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cat_offline',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название (кнопки)'),
        ),
        migrations.AlterField(
            model_name='cat_offline',
            name='sub_desc',
            field=models.TextField(null=True, verbose_name='Под описание'),
        ),
        migrations.AlterField(
            model_name='connect_admin',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='connect_admin',
            name='keyb_text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='keys_text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='url',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='calls_price',
            field=models.CharField(blank=True, default="💻 Онлайн консультация (звонок/видео) – 20$⌛️30 минут^^^💻 Onlayn maslahat (qo'ng'iroq/video) – 20$⌛️30 daqiqa", max_length=350, null=True, verbose_name='Цена консультации(звонок/видео)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='cat_offline',
            field=models.ManyToManyField(related_name='subcat_set', to='infos.sub_cat_offline', verbose_name='Категории консультации'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='chat_price',
            field=models.CharField(blank=True, default='💬 Консультация в чате – 14$ ^^^💬 Chatda maslahat – $14', max_length=350, null=True, verbose_name='Цена консультации(чат)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='consult_type',
            field=models.TextField(choices=[('calls', 'Calls'), ('chat', 'Chat'), ('calls/chat', 'Calls/Chat')], default='calls/chat', max_length=150, verbose_name='Тип консультации'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='full_name',
            field=models.CharField(max_length=250, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='location',
            field=models.CharField(blank=True, max_length=450, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='offline_price',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Цена консультации(оффлайн)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='online_price',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Цена консультации(онлайн)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='prof',
            field=models.CharField(max_length=150, null=True, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='work_type',
            field=models.TextField(choices=[('online', 'Online'), ('offline', 'Offline'), ('online/offline', 'Online/Offline')], default='online/offline', max_length=150, verbose_name='Тип работы'),
        ),
        migrations.AlterField(
            model_name='group_info',
            name='description',
            field=models.TextField(blank=True, default='админ добавь!!!', null=True, verbose_name='Инструкция'),
        ),
        migrations.AlterField(
            model_name='group_info',
            name='doctor_user_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ID доктора'),
        ),
        migrations.AlterField(
            model_name='group_info',
            name='group_id',
            field=models.BigIntegerField(verbose_name='ID группы'),
        ),
        migrations.AlterField(
            model_name='group_info',
            name='link_group',
            field=models.CharField(default='https://t.me/+q1L8DFcf0UplZWVi', max_length=350, verbose_name='Ссылка на группу'),
        ),
        migrations.AlterField(
            model_name='group_info',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='group_info',
            name='pacient_userid',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ID пациента'),
        ),
        migrations.AlterField(
            model_name='group_info',
            name='status_working',
            field=models.BooleanField(default=False, verbose_name='Статус работы'),
        ),
        migrations.AlterField(
            model_name='group_info',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='group_info',
            name='users_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ID пользователей'),
        ),
        migrations.AlterField(
            model_name='laboratory_analice',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='laboratory_analice',
            name='keyb_text',
            field=models.CharField(blank=True, default='Открыть в Google Maps', max_length=250, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='laboratory_analice',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mskt_book',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mskt_book',
            name='keyb_text',
            field=models.CharField(blank=True, default='Открыть в Google Maps', max_length=250, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='mskt_book',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pacient_info',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='pacient_info',
            name='total',
            field=models.TextField(blank=True, null=True, verbose_name='Всего'),
        ),
        migrations.AlterField(
            model_name='pacient_info',
            name='type',
            field=models.CharField(choices=[('dates', 'Dates'), ('question', 'Question')], default='dates', max_length=50, verbose_name='Тип данных'),
        ),
        migrations.AlterField(
            model_name='pacient_info',
            name='type_consult',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип консультации'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name_provider',
            field=models.CharField(max_length=250, verbose_name='Название платежной системы'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='token',
            field=models.CharField(max_length=250, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='payment_history',
            name='amount',
            field=models.CharField(max_length=250, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment_history',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='payment_history',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='doctors_ques',
            field=models.TextField(blank=True, null=True, verbose_name='Другие тексты'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='faq_text',
            field=models.TextField(verbose_name='Часто задаваемые вопросы'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='keyb_quest',
            field=models.TextField(blank=True, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='let_text',
            field=models.TextField(verbose_name='запрос текст'),
        ),
        migrations.AlterField(
            model_name='recomended_centers',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recomended_centers',
            name='keyb_text',
            field=models.CharField(blank=True, default='Открыть в Google Maps', max_length=250, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='recomended_centers',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sub_cat_offline',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название (кнопки)'),
        ),
    ]
