# Generated by Django 4.2.5 on 2023-10-02 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0033_alter_payment_history_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Город',
            },
        ),
        migrations.CreateModel(
            name='clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clinic/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиника',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктор',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infos.city')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регион',
            },
        ),
        migrations.RemoveField(
            model_name='about',
            name='head',
        ),
        migrations.DeleteModel(
            name='admin_info',
        ),
        migrations.DeleteModel(
            name='another_text',
        ),
        migrations.RemoveField(
            model_name='cat_offline',
            name='head',
        ),
        migrations.RemoveField(
            model_name='connect_admin',
            name='head',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='head',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='cat_offline',
        ),
        migrations.DeleteModel(
            name='Group_info',
        ),
        migrations.RemoveField(
            model_name='laboratory_analice',
            name='head',
        ),
        migrations.RemoveField(
            model_name='mskt_book',
            name='head',
        ),
        migrations.RemoveField(
            model_name='pacient_info',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='payment_history',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='head',
        ),
        migrations.RemoveField(
            model_name='recomended_centers',
            name='head',
        ),
        migrations.RemoveField(
            model_name='sub_cat_offline',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='users',
            name='language_code',
        ),
        migrations.AddField(
            model_name='users',
            name='status_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='type_person',
            field=models.CharField(choices=[('DR', 'Doktor'), ('OE', 'Owner')], default='OE', max_length=2),
        ),
        migrations.DeleteModel(
            name='about',
        ),
        migrations.DeleteModel(
            name='cat_offline',
        ),
        migrations.DeleteModel(
            name='connect_admin',
        ),
        migrations.DeleteModel(
            name='detail',
        ),
        migrations.DeleteModel(
            name='doctors',
        ),
        migrations.DeleteModel(
            name='Head',
        ),
        migrations.DeleteModel(
            name='laboratory_analice',
        ),
        migrations.DeleteModel(
            name='mskt_book',
        ),
        migrations.DeleteModel(
            name='pacient_info',
        ),
        migrations.DeleteModel(
            name='questions',
        ),
        migrations.DeleteModel(
            name='recomended_centers',
        ),
        migrations.DeleteModel(
            name='sub_cat_offline',
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='infos.users'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='work_region',
            field=models.ManyToManyField(related_name='region_set', to='infos.region'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_set', to='infos.doctor'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infos.region'),
        ),
    ]
