# Generated by Django 4.2.5 on 2023-10-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0034_city_clinic_doctor_region_remove_about_head_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
