# Generated by Django 4.2.5 on 2023-10-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0035_rename_users_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
