# Generated by Django 4.2.5 on 2023-10-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0039_admin_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
