# Generated by Django 4.2.5 on 2023-10-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0042_alter_clinic_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
