# Generated by Django 4.2.5 on 2023-10-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0044_doctor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='type_clinic',
            field=models.CharField(choices=[('VT', 'VetApteka'), ('KL', 'Klinika')], default='KL', max_length=2),
        ),
    ]
