# Generated by Django 4.2.5 on 2023-10-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0045_clinic_type_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
