# Generated by Django 4.2.5 on 2023-10-11 09:47

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0046_doctor_description_ru'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='city',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
